baseURL: 'http://www.bookreviews.io/'
languageCode: 'en-us'
title: "Tarik's Book Reviews"
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  author: ["Tarik Guney"]
  keywords: [Book Reviews, Book Review, Tarik Book Reviews]
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  DateFormat: "January 2, 2006"
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowShareButtons: true
  homeInfoParams:
    Title: "Hey, I am Tarik Guney!"
    Content: "I love reading books! And I often share my reviews of them, which are typically what I learned as I was reading. You can find my book reviews on this site. You can find me at LinkedIn and Github!"
  socialIcons:
    - name: "linkedin"
      url: "https://linkedin.com/in/tarikguney"
    - name: "github"
      url: "https://github.com/tarikguney"
  editPost:
    URL: "https://github.com/tarikguney/book-reviews/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link